CodeSystem: CodeSystemLocalComponentCodes
Id: CodeSystem-local-component-codes
Title: "CodeSystem - Local Component Codes"
Description: """Local Component Codes for observation components that lack an appropriate LOINC code.
The MDI CodeSystem - Local Component Codes artifact overlaps with the VRDR Local Component Codes artifact."""
* ^status = #active
* ^experimental = false
* ^caseSensitive = false
* ^content = #complete
* ^count = 64
* #position "position"
* #lineNumber "line number"
* #eCodeIndicator "e Code Indicator"
* #wouldBeUnderlyingCauseOfDeathWithoutPregnancy "Would be underlying cause of death without pregnancy."
* #EmergingIssue1_1 "EmergingIssue1_1"
* #EmergingIssue1_2 "EmergingIssue1_2"
* #EmergingIssue1_3 "EmergingIssue1_3"
* #EmergingIssue1_4 "EmergingIssue1_4"
* #EmergingIssue1_5 "EmergingIssue1_5"
* #EmergingIssue1_6 "EmergingIssue1_6"
* #EmergingIssue1_7 "EmergingIssue1_7"
* #EmergingIssue1_8 "EmergingIssue1_8"
* #EmergingIssue8_1 "EmergingIssue8_1"
* #EmergingIssue8_2 "EmergingIssue8_2"
* #EmergingIssue8_3 "EmergingIssue8_3"
* #EmergingIssue20 "EmergingIssue20"
* #FirstEditedCode "First Edited Race Code"
* #SecondEditedCode "Second Edited Race Code"
* #ThirdEditedCode "Third Edited Race Code"
* #FourthEditedCode "Fourth Edited Race Code"
* #FifthEditedCode "Fifth Edited Race Code"
* #SixthEditedCode "Sixth Edited Race Code"
* #SeventhEditedCode "Seventh Edited Race Code"
* #EighthEditedCode "Eighth Edited Race Code"
* #FirstAmericanIndianCode "First Edited American Indian Race Code"
* #SecondAmericanIndianCode "Second Edited American Indian Race Code"
* #FirstOtherAsianCode "First Edited Other Asian Race Code"
* #SecondOtherAsianCode "Second Edited Other Asian Race Race Code"
* #FirstOtherPacificIslanderCode "First Edited Other Pacific Islander Race Code"
* #SecondOtherPacificIslanderCode "First Edited Other Pacific Islander Race Code"
* #FirstOtherRaceCode "First Edited Other Race Code"
* #SecondOtherRaceCode "First Edited Other Race Code"
* #RaceRecode40 "Race Recode 40"
* #HispanicCode "Hispanic Code"
* #HispanicCodeForLiteral "Hispanic Code for Literal"
* #RACEMVR "Race Missing Value Reason"
* #HispanicMexican "Hispanic Mexican"
* #HispanicPuertoRican "Hispanic Puerto Rican"
* #HispanicCuban "Hispanic Cuban"
* #HispanicOther "Hispanic Other"
* #HispanicLiteral "Hispanic Literal"
* #White "White"
* #BlackOrAfricanAmerican "Black Or African American"
* #AmericanIndianOrAlaskanNative "American Indian Or Alaska Native"
* #AsianIndian "Asian Indian"
* #Chinese "Chinese"
* #Filipino "Filipino"
* #Japanese "Japanese"
* #Korean "Korean"
* #Vietnamese "Vietnamese"
* #OtherAsian "OtherAsian"
* #NativeHawaiian "Native Hawaiian"
* #GuamanianOrChamorro "Guamanian Or Chamorro"
* #Samoan "Samoan"
* #OtherPacificIslander "Other Pacific Islander"
* #OtherRace "Other Race"
* #FirstAmericanIndianOrAlaskanNativeLiteral "First American Indian Or Alaska Native Literal"
* #SecondAmericanIndianOrAlaskanNativeLiteral "Second American Indian Or Alaska Native Literal"
* #FirstOtherAsianLiteral "First Other Asian Literal"
* #SecondOtherAsianLiteral "Second Other Asian Literal"
* #FirstOtherPacificIslanderLiteral "First Other Pacific Islander Literal"
* #SecondOtherPacificIslanderLiteral "Second Other Pacific Islander Literal"
* #FirstOtherRaceLiteral "First Other Race Literal"
* #SecondOtherRaceLiteral "Second Other Race Literal"